import { KalturaObjectMetadata } from '../kaltura-object-base';
import { KalturaStorageProfileStatus } from './KalturaStorageProfileStatus';
import { KalturaStorageProfileProtocol } from './KalturaStorageProfileProtocol';
import { KalturaKeyValue } from './KalturaKeyValue';
import { KalturaStorageProfileDeliveryStatus } from './KalturaStorageProfileDeliveryStatus';
import { KalturaStorageProfileReadyBehavior } from './KalturaStorageProfileReadyBehavior';
import { KalturaRule } from './KalturaRule';
import { KalturaObjectBase, KalturaObjectBaseArgs } from '../kaltura-object-base';
export interface KalturaStorageProfileArgs extends KalturaObjectBaseArgs {
    name?: string;
    systemName?: string;
    desciption?: string;
    status?: KalturaStorageProfileStatus;
    protocol?: KalturaStorageProfileProtocol;
    storageUrl?: string;
    storageBaseDir?: string;
    storageUsername?: string;
    storagePassword?: string;
    storageFtpPassiveMode?: boolean;
    minFileSize?: number;
    maxFileSize?: number;
    flavorParamsIds?: string;
    maxConcurrentConnections?: number;
    pathManagerClass?: string;
    pathManagerParams?: KalturaKeyValue[];
    trigger?: number;
    deliveryPriority?: number;
    deliveryStatus?: KalturaStorageProfileDeliveryStatus;
    readyBehavior?: KalturaStorageProfileReadyBehavior;
    allowAutoDelete?: number;
    createFileLink?: boolean;
    rules?: KalturaRule[];
    deliveryProfileIds?: KalturaKeyValue[];
    privateKey?: string;
    publicKey?: string;
    passPhrase?: string;
    shouldExportThumbs?: boolean;
}
export declare class KalturaStorageProfile extends KalturaObjectBase {
    readonly id: number;
    readonly createdAt: Date;
    readonly updatedAt: Date;
    readonly partnerId: number;
    name: string;
    systemName: string;
    desciption: string;
    status: KalturaStorageProfileStatus;
    protocol: KalturaStorageProfileProtocol;
    storageUrl: string;
    storageBaseDir: string;
    storageUsername: string;
    storagePassword: string;
    storageFtpPassiveMode: boolean;
    minFileSize: number;
    maxFileSize: number;
    flavorParamsIds: string;
    maxConcurrentConnections: number;
    pathManagerClass: string;
    pathManagerParams: KalturaKeyValue[];
    trigger: number;
    deliveryPriority: number;
    deliveryStatus: KalturaStorageProfileDeliveryStatus;
    readyBehavior: KalturaStorageProfileReadyBehavior;
    allowAutoDelete: number;
    createFileLink: boolean;
    rules: KalturaRule[];
    deliveryProfileIds: KalturaKeyValue[];
    privateKey: string;
    publicKey: string;
    passPhrase: string;
    shouldExportThumbs: boolean;
    constructor(data?: KalturaStorageProfileArgs);
    protected _getMetadata(): KalturaObjectMetadata;
}
