import { KalturaObjectMetadata } from '../kaltura-object-base';
import { KalturaEntryStatus } from './KalturaEntryStatus';
import { KalturaEntryModerationStatus } from './KalturaEntryModerationStatus';
import { KalturaEntryType } from './KalturaEntryType';
import { KalturaLicenseType } from './KalturaLicenseType';
import { KalturaEntryReplacementStatus } from './KalturaEntryReplacementStatus';
import { KalturaOperationAttributes } from './KalturaOperationAttributes';
import { KalturaEntryDisplayInSearchType } from './KalturaEntryDisplayInSearchType';
import { KalturaObjectBase, KalturaObjectBaseArgs } from '../kaltura-object-base';
export interface KalturaBaseEntryArgs extends KalturaObjectBaseArgs {
    name?: string;
    description?: string;
    userId?: string;
    creatorId?: string;
    tags?: string;
    adminTags?: string;
    categories?: string;
    categoriesIds?: string;
    type?: KalturaEntryType;
    groupId?: number;
    partnerData?: string;
    licenseType?: KalturaLicenseType;
    accessControlId?: number;
    startDate?: Date;
    endDate?: Date;
    referenceId?: string;
    partnerSortValue?: number;
    conversionProfileId?: number;
    redirectEntryId?: string;
    parentEntryId?: string;
    operationAttributes?: KalturaOperationAttributes[];
    entitledUsersEdit?: string;
    entitledUsersPublish?: string;
    entitledUsersView?: string;
    templateEntryId?: string;
    displayInSearch?: KalturaEntryDisplayInSearchType;
}
export declare class KalturaBaseEntry extends KalturaObjectBase {
    readonly id: string;
    name: string;
    description: string;
    readonly partnerId: number;
    userId: string;
    creatorId: string;
    tags: string;
    adminTags: string;
    categories: string;
    categoriesIds: string;
    readonly status: KalturaEntryStatus;
    readonly moderationStatus: KalturaEntryModerationStatus;
    readonly moderationCount: number;
    type: KalturaEntryType;
    readonly createdAt: Date;
    readonly updatedAt: Date;
    readonly rank: number;
    readonly totalRank: number;
    readonly votes: number;
    groupId: number;
    partnerData: string;
    readonly downloadUrl: string;
    readonly searchText: string;
    licenseType: KalturaLicenseType;
    readonly version: number;
    readonly thumbnailUrl: string;
    accessControlId: number;
    startDate: Date;
    endDate: Date;
    referenceId: string;
    readonly replacingEntryId: string;
    readonly replacedEntryId: string;
    readonly replacementStatus: KalturaEntryReplacementStatus;
    partnerSortValue: number;
    conversionProfileId: number;
    redirectEntryId: string;
    readonly rootEntryId: string;
    parentEntryId: string;
    operationAttributes: KalturaOperationAttributes[];
    entitledUsersEdit: string;
    entitledUsersPublish: string;
    entitledUsersView: string;
    readonly capabilities: string;
    templateEntryId: string;
    displayInSearch: KalturaEntryDisplayInSearchType;
    constructor(data?: KalturaBaseEntryArgs);
    protected _getMetadata(): KalturaObjectMetadata;
}
