import { KalturaObjectMetadata } from '../kaltura-object-base';
import { KalturaUserType } from './KalturaUserType';
import { KalturaGender } from './KalturaGender';
import { KalturaUserStatus } from './KalturaUserStatus';
import { KalturaLanguageCode } from './KalturaLanguageCode';
import { KalturaObjectBase, KalturaObjectBaseArgs } from '../kaltura-object-base';
export interface KalturaUserArgs extends KalturaObjectBaseArgs {
    id?: string;
    type?: KalturaUserType;
    screenName?: string;
    fullName?: string;
    email?: string;
    dateOfBirth?: number;
    country?: string;
    state?: string;
    city?: string;
    zip?: string;
    thumbnailUrl?: string;
    description?: string;
    tags?: string;
    adminTags?: string;
    gender?: KalturaGender;
    status?: KalturaUserStatus;
    partnerData?: string;
    indexedPartnerDataInt?: number;
    indexedPartnerDataString?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
    isAdmin?: boolean;
    language?: KalturaLanguageCode;
    loginEnabled?: boolean;
    roleIds?: string;
    isAccountOwner?: boolean;
    allowedPartnerIds?: string;
    allowedPartnerPackages?: string;
}
export declare class KalturaUser extends KalturaObjectBase {
    id: string;
    readonly partnerId: number;
    type: KalturaUserType;
    screenName: string;
    fullName: string;
    email: string;
    dateOfBirth: number;
    country: string;
    state: string;
    city: string;
    zip: string;
    thumbnailUrl: string;
    description: string;
    tags: string;
    adminTags: string;
    gender: KalturaGender;
    status: KalturaUserStatus;
    readonly createdAt: Date;
    readonly updatedAt: Date;
    partnerData: string;
    indexedPartnerDataInt: number;
    indexedPartnerDataString: string;
    readonly storageSize: number;
    password: string;
    firstName: string;
    lastName: string;
    isAdmin: boolean;
    language: KalturaLanguageCode;
    readonly lastLoginTime: number;
    readonly statusUpdatedAt: number;
    readonly deletedAt: Date;
    loginEnabled: boolean;
    roleIds: string;
    readonly roleNames: string;
    isAccountOwner: boolean;
    allowedPartnerIds: string;
    allowedPartnerPackages: string;
    constructor(data?: KalturaUserArgs);
    protected _getMetadata(): KalturaObjectMetadata;
}
